os:
- linux
language: go
go: 1.13.5
go_import_path: github.com/hunterlong/statping
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
  - "$GOPATH/src/github.com/hunterlong/statping/vendor"
sudo: required
services:
- docker
- postgresql
- mysql
- mongodb
env:
  global:
  - PATH=/snap/bin:$PATH
  - DB_HOST=localhost
  - DB_USER=travis
  - DB_PASS=
  - DB_DATABASE=test
  - GO_ENV=test
  - STATPING_DIR=$GOPATH/src/github.com/hunterlong/statping
  - secure: CAVxMvW04wS/APA6QGjlWjLfTx5hc+TWwCKuBkMV2MioZSQGOTQBC4nITySUwepAFY25mI8zNV5oROOKzG0FxYvr2iIqKDkTTdVF1+XS2uyHfEKlsWMPErcqkGjRksDil75Pckz15uvvOYPndetK2QiamQkSf9U8dUJgzrPuV+UOFj6RO/kkEWhzmoyTdVdwIRKmiL8jINkvvFOWCAfg3WlBmucgYHHqjqeTn1kSeUJ+DV9lF8+ENq+74GZrnsq26UtskJexywDeFhhUYjWEvOFXQ19txB/JrvdZ2KSkYeuhHr1ZxlENSpQ/rySQqBvg7+XAl1RhQlL5V7/feXA+I/COqNYG5KqbDgeSUwGkZIumz1ITi24Lz4xATG5hnuRQkOIaO8/FGHAeQxU0JcdWlzS8M5RpvpN9tT12XSFDPYswFmkO+gGSEpu+2gSEbiaX7qocLLvZiMpkQxfOmItaUW5ZMXRvTWijhQTb2nyPOQ9JEabuAtAUrCwe7Enmc8P8ZasNZaJLJO53iQ8FyzrNFyAFwY5F87OQ/v3Hnjv0ADG8fDc4VUxlj8TweuRzETT8U2hchxqnK4BON2WMSj4d1V96pDuzb5fArtq5PTbI4VB7mZPriXYZEiKdfLEIufOYhg7uKdNRekMLkuJRr+ttH0Gyb+lILzSiHMHwxOH5bfM=
matrix:
  allow_failures:
  - go: master
  fast_finish: true
notifications:
  email: true
branches:
  only:
  - master
install:
- npm install -g sass
- npm install -g newman
- go mod vendor
- make dev-deps
- make install
before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- psql -c 'create database test;' -U postgres
script:
- travis_retry make test-all
- make test-api
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then
  make coverage; fi
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then
  make travis-build; fi
webhooks:
  urls:
  - "$GITTER"
  on_success: change
  on_failure: always
  on_start: never
