os:
  - linux

language: go

go:
  - "1.10.x"

install: true

sudo: required

services:
  - docker
  - postgresql
  - mysql
  - mongodb

env:
  global:
    - DB_HOST=localhost
    - DB_USER=travis
    - DB_PASS=
    - DB_DATABASE=test
    - GO_ENV=test
    - STATUP_DIR=$GOPATH/src/github.com/hunterlong/statup

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_deploy:
  - git config --local user.name "hunterlong"
  - git config --local user.email "info@socialeck.com"
  - make tag
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file:
      - "build/statup-osx-x64.tar.gz"
      - "build/statup-osx-x32.tar.gz"
      - "build/statup-linux-x64.tar.gz"
      - "build/statup-linux-x32.tar.gz"
      - "build/statup-linux-arm64.tar.gz"
      - "build/statup-linux-arm7.tar.gz"
      - "build/statup-linux-alpine.tar.gz"
      - "build/statup-windows-x64.zip"
    skip_cleanup: true

notifications:
  email: false

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - psql -c 'create database test;' -U postgres
  - make deps
  - make install

script:
  - make test
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then make coverage; fi

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then travis_wait 30 docker pull karalabe/xgo-latest; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then make release; fi

after_deploy:
  - make publish
