os:
  - linux

language: go

go:
  - "1.10.x"

go_import_path: github.com/hunterlong/statup

install: true

sudo: required

services:
  - docker
  - postgresql
  - mysql
  - mongodb

env:
  global:
    - DB_HOST=localhost
    - DB_USER=travis
    - DB_PASS=
    - DB_DATABASE=test
    - GO_ENV=test
    - STATUP_DIR=$GOPATH/src/github.com/hunterlong/statup

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - psql -c 'create database test;' -U postgres
  - gem install sass
  - wget -q https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
  - chmod +x dep-linux-amd64
  - sudo mv dep-linux-amd64 /usr/local/bin/dep
  - make dev-deps
  - make dep
  - make install

script:
  - make test-all
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then make coverage; fi

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then travis-build; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then publish-dev; fi
