os:
  - linux

language: go

go:
  - "1.10.x"

install: true

sudo: required

services:
  - docker
  - postgresql
  - mysql
  - mongodb

env:
  - VERSION=0.17

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_deploy:
  - git config --local user.name "hunterlong"
  - git config --local user.email "info@socialeck.com"
  - git tag "v$VERSION" --force
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file:
      - "build/statup-osx-x64"
      - "build/statup-osx-x32"
      - "build/statup-linux-x64"
      - "build/statup-linux-x32"
      - "build/statup-windows-x64.exe"
    skip_cleanup: true

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then travis_wait 30 docker pull karalabe/xgo-latest; fi

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then /bin/bash -c ./build.sh; fi
  - curl -X POST $DOCKER > /dev/null

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - psql -c 'create database test;' -U postgres
  - go get github.com/stretchr/testify/assert
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/rendon/testcli
  - go get github.com/karalabe/xgo
  - go get github.com/GeertJohan/go.rice
  - go get github.com/GeertJohan/go.rice/rice
  - go get
  - go install

script:
  - go test -v