version: '3.7'

services:

  statping:
    container_name: statping
    image: hunterlong/statping:latest
    restart: always
    volumes:
      - statping_data:/app
    environment:
      DB_CONN: sqlite
    ports:
      - 8080:8080
