version: '2.4'

services:

  sut:
    build:
      context: .
      dockerfile: ./Dockerfile.base
    links:
      - postgres
    depends_on:
      - postgres
    entrypoint: make test
    environment:
      DB_CONN: postgres
      DB_USER: root
      DB_PASS: password123
      DB_HOST: postgres
      DB_DATABASE: statping
      API_KEY: exampleapikey
      API_SECRET: exampleapisecret
      NAME: Statping Testing
      DOMAIN: http://localhost:8080
      DESCRIPTION: This is a TESTING environment
      ADMIN_USER: admin
      ADMIN_PASS: admin

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: statping
      POSTGRES_USER: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 15s
      timeout: 10s
      retries: 20
