name: statup
version: 0.79.91
summary: Statup Server Monitoring with Status Page
description: >
  An easy to use Status Page for your websites and applications.
  Statup will automatically fetch the application and render a beautiful
  status page with tons of features for you to build an even better status page.
  This Status Page generator allows you to use MySQL, Postgres, or SQLite
  on multiple operating systems.

type: app
confinement: strict
grade: stable

parts:
  statup:
    plugin: dump
    source: https://github.com/hunterlong/statup/releases/download/v$SNAPCRAFT_PROJECT_VERSION/statup-linux-x64.tar.gz

apps:
  statup:
    command: statup