name: statping
version-script: cat version.txt
version: "stable"
summary: Statping Server Monitoring with Status Page
description: >
  An easy to use Status Page for your websites and applications.
  Statping will automatically fetch the application and render a beautiful
  status page with tons of features for you to build an even better status page.
  This Status Page generator allows you to use MySQL, Postgres, or SQLite
  on multiple operating systems.

type: app
confinement: strict
grade: stable
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

adopt-info: statping

apps:
  statping:
    command: statping
    plugs:
      - home
      - network
      - network-bind

parts:
  statping:
  plugin: git
    source: https://github.com/statping/statping.git
    source-type: git
    override-pull: |
      snapcraftctl set-version "$(cat version.txt)"
    override-build: |
      export GOPATH=$PWD
      cd src/github.com/statping/statping
      GOOS=linux go build -a -ldflags "-s -w -extldflags -static -X main.VERSION=$(cat version.txt)" -o statping --tags "netgo linux" ./cmd
    build-snaps:
      - go
    build-packages:
      - git
      - sed

