version: '3.1'

services:

  statping:
    hostname: statping
    image: statping/statping
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      SERVICES: '[{"name": "Local Statping", "type": "http", "domain": "http://localhost:8585", "interval": 30}]'
      DB_CONN: sqlite
      API_KEY: exampleapikey
      API_SECRET: exampleapisecret
      NAME: Statping on SQLite
      DOMAIN: http://localhost:8080
      DESCRIPTION: This is a dev environment on SQLite!
      ADMIN_USER: admin
      ADMIN_PASS: admin
