version: '2.3'

services:

  statping:
    container_name: statping
    image: hunterlong/statping:latest
    restart: always
    ports:
      - 0.0.0.0:80:8080
    volumes:
      - ./statping/app:/app
    environment:
      NAME: Single Docker Image
      DESCRIPTION: You'll need to input your own Database information in Setup process