version: '2.3'

services:

  statup:
    container_name: statup
    image: hunterlong/statup:dev
    networks:
      - internet
      - database
    depends_on:
      - postgres_statup
      - postgres_mysql
    entrypoint:
      - "sleep 30 && cd /go/src/github.com/hunterlong/statup && go test -v ./..."
    environment:
      GO_ENV: test
      DB_CONN: postgres
      DB_HOST: postgres_statup
      DB_USER: root
      DB_PASS: root
      DB_DATABASE: statup
      NAME: EC2 Example
      DESCRIPTION: This is a Statup Docker Compose instance

  postgres_statup:
    container_name: postgres_statup
    image: postgres
    restart: always
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: statup
      POSTGRES_DB: statup

  postgres_mysql:
    container_name: mysql_statup
    image: mysql
    restart: always
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: statup

networks:
  internet:
    driver: bridge
  database:
    driver: bridge