name: Statping Build and Deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.x'

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Dependencies
        run: npm install -g yarn sass newman cross-env wait-on @sentry/cli

      - name: Checkout Statping
        uses: actions/checkout@v2

      - name: Download Frontend Dependencies
        working-directory: ./frontend
        run: yarn

      - name: Download Go mods
        run: |
          go mod download
          go mod verify

      - name: Build Frontend Statping
        run: make clean compile

      - name: Install Statping
        run: make install

      - name: Test Statping
        env:
          DB_CONN: sqlite3
        run: SASS=`which sass` go test -v -covermode=count -coverprofile=coverage.out -p=1 ./...

      - name: Build Binaries
        run: make build-bin build-win
